# Site configuration
theme: # Not using a theme
plugins:
- jekyll-feed
title: blog.matiboux.me
description: Matiboux's blog
author: Matiboux
lang: en

# Blog configuration
permalink: /:categories/:title
excerpt_separator: <!--more-->

# Jekyll confiuration
exclude: [CNAME, LICENSE, README.md]
